#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
LOCATION=$(dirname $SCRIPT_DIR)
set -o errexit
set -o pipefail
set -o nounset

cd "$LOCATION"
bash "$SCRIPT_DIR/django-bootstrap"
exec python3 ./uvicorn_main.py $*
