# Generated by Django 5.2.3 on 2025-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_alter_event_shirt_sizes_alter_helper_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Grade or Department'),
        ),
    ]
