# Generated by Django 5.2.1 on 2025-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0066_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ask_grade",
            field=models.BooleanField(default=True, verbose_name="Ask for grade"),
        ),
    ]
